name: Push DLL on Merge

on:
  pull_request:
    types: [closed]

jobs:
  push_dll:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: dotnet build --configuration Release

     
